// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: control.proto

package control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobStatusEnum: Status of a job execution
type JobStatusEnum int32

const (
	JobStatusEnum_JOB_STATUS_UNKNOWN   JobStatusEnum = 0
	JobStatusEnum_JOB_STATUS_ASSIGNED  JobStatusEnum = 1 // Job assigned to agent (optional, for M2+)
	JobStatusEnum_JOB_STATUS_RUNNING   JobStatusEnum = 2
	JobStatusEnum_JOB_STATUS_SUCCEEDED JobStatusEnum = 3
	JobStatusEnum_JOB_STATUS_FAILED    JobStatusEnum = 4
	JobStatusEnum_JOB_STATUS_CANCELED  JobStatusEnum = 5 // Job canceled by user/admin
	JobStatusEnum_JOB_STATUS_LOST      JobStatusEnum = 6 // Job lost due to agent disconnect/lease expiry (M2+)
)

// Enum value maps for JobStatusEnum.
var (
	JobStatusEnum_name = map[int32]string{
		0: "JOB_STATUS_UNKNOWN",
		1: "JOB_STATUS_ASSIGNED",
		2: "JOB_STATUS_RUNNING",
		3: "JOB_STATUS_SUCCEEDED",
		4: "JOB_STATUS_FAILED",
		5: "JOB_STATUS_CANCELED",
		6: "JOB_STATUS_LOST",
	}
	JobStatusEnum_value = map[string]int32{
		"JOB_STATUS_UNKNOWN":   0,
		"JOB_STATUS_ASSIGNED":  1,
		"JOB_STATUS_RUNNING":   2,
		"JOB_STATUS_SUCCEEDED": 3,
		"JOB_STATUS_FAILED":    4,
		"JOB_STATUS_CANCELED":  5,
		"JOB_STATUS_LOST":      6,
	}
)

func (x JobStatusEnum) Enum() *JobStatusEnum {
	p := new(JobStatusEnum)
	*p = x
	return p
}

func (x JobStatusEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatusEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[0].Descriptor()
}

func (JobStatusEnum) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[0]
}

func (x JobStatusEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatusEnum.Descriptor instead.
func (JobStatusEnum) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

// JobTypeEnum: Job execution type
type JobTypeEnum int32

const (
	JobTypeEnum_JOB_TYPE_UNKNOWN      JobTypeEnum = 0
	JobTypeEnum_JOB_TYPE_COMMAND      JobTypeEnum = 1 // Execute command on agent
	JobTypeEnum_JOB_TYPE_FORWARD_HTTP JobTypeEnum = 2 // Forward request to local HTTP service on agent
)

// Enum value maps for JobTypeEnum.
var (
	JobTypeEnum_name = map[int32]string{
		0: "JOB_TYPE_UNKNOWN",
		1: "JOB_TYPE_COMMAND",
		2: "JOB_TYPE_FORWARD_HTTP",
	}
	JobTypeEnum_value = map[string]int32{
		"JOB_TYPE_UNKNOWN":      0,
		"JOB_TYPE_COMMAND":      1,
		"JOB_TYPE_FORWARD_HTTP": 2,
	}
)

func (x JobTypeEnum) Enum() *JobTypeEnum {
	p := new(JobTypeEnum)
	*p = x
	return p
}

func (x JobTypeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobTypeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[1].Descriptor()
}

func (JobTypeEnum) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[1]
}

func (x JobTypeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobTypeEnum.Descriptor instead.
func (JobTypeEnum) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

// InputForwardMode: how input file is forwarded to local service
type InputForwardMode int32

const (
	InputForwardMode_INPUT_FORWARD_MODE_UNSPECIFIED InputForwardMode = 0
	InputForwardMode_INPUT_FORWARD_MODE_URL         InputForwardMode = 1 // Provide presigned URL to local service
	InputForwardMode_INPUT_FORWARD_MODE_LOCAL_FILE  InputForwardMode = 2 // Download and send file to local service
)

// Enum value maps for InputForwardMode.
var (
	InputForwardMode_name = map[int32]string{
		0: "INPUT_FORWARD_MODE_UNSPECIFIED",
		1: "INPUT_FORWARD_MODE_URL",
		2: "INPUT_FORWARD_MODE_LOCAL_FILE",
	}
	InputForwardMode_value = map[string]int32{
		"INPUT_FORWARD_MODE_UNSPECIFIED": 0,
		"INPUT_FORWARD_MODE_URL":         1,
		"INPUT_FORWARD_MODE_LOCAL_FILE":  2,
	}
)

func (x InputForwardMode) Enum() *InputForwardMode {
	p := new(InputForwardMode)
	*p = x
	return p
}

func (x InputForwardMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InputForwardMode) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[2].Descriptor()
}

func (InputForwardMode) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[2]
}

func (x InputForwardMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InputForwardMode.Descriptor instead.
func (InputForwardMode) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

// Envelope wraps all messages for forward compatibility
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent_id: Set by agent for agent-originated messages.
	// VALIDATION RULE: If payload message also contains agent_id field, it MUST equal Envelope.agent_id.
	// Server must reject messages where this consistency check fails (prevents cross-agent confusion).
	AgentId   string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RequestId string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // UUID for tracing
	Timestamp int64  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // Unix milliseconds
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Register
	//	*Envelope_Heartbeat
	//	*Envelope_RegisterAck
	//	*Envelope_HeartbeatAck
	//	*Envelope_RequestJob
	//	*Envelope_JobAssigned
	//	*Envelope_JobStatus
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Envelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Envelope) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *Envelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Envelope) GetRegisterAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *Envelope) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *Envelope) GetRequestJob() *RequestJob {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RequestJob); ok {
			return x.RequestJob
		}
	}
	return nil
}

func (x *Envelope) GetJobAssigned() *JobAssigned {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_JobAssigned); ok {
			return x.JobAssigned
		}
	}
	return nil
}

func (x *Envelope) GetJobStatus() *JobStatus {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_JobStatus); ok {
			return x.JobStatus
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Register struct {
	Register *Register `protobuf:"bytes,10,opt,name=register,proto3,oneof"`
}

type Envelope_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type Envelope_RegisterAck struct {
	RegisterAck *RegisterAck `protobuf:"bytes,12,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type Envelope_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,13,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type Envelope_RequestJob struct {
	RequestJob *RequestJob `protobuf:"bytes,14,opt,name=request_job,json=requestJob,proto3,oneof"`
}

type Envelope_JobAssigned struct {
	JobAssigned *JobAssigned `protobuf:"bytes,15,opt,name=job_assigned,json=jobAssigned,proto3,oneof"`
}

type Envelope_JobStatus struct {
	JobStatus *JobStatus `protobuf:"bytes,16,opt,name=job_status,json=jobStatus,proto3,oneof"`
}

func (*Envelope_Register) isEnvelope_Payload() {}

func (*Envelope_Heartbeat) isEnvelope_Payload() {}

func (*Envelope_RegisterAck) isEnvelope_Payload() {}

func (*Envelope_HeartbeatAck) isEnvelope_Payload() {}

func (*Envelope_RequestJob) isEnvelope_Payload() {}

func (*Envelope_JobAssigned) isEnvelope_Payload() {}

func (*Envelope_JobStatus) isEnvelope_Payload() {}

// Register: Agent registers with cloud on connection
type Register struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent_id: Must equal Envelope.agent_id if present (server validates consistency)
	AgentId        string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentToken     string `protobuf:"bytes,2,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"` // Pre-shared secret (MVP)
	Hostname       string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	MaxConcurrency int32  `protobuf:"varint,4,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"` // Default 1
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *Register) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Register) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

func (x *Register) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Register) GetMaxConcurrency() int32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

// RegisterAck: Server acknowledges registration
type RegisterAck struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Success              bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	HeartbeatIntervalSec int32                  `protobuf:"varint,3,opt,name=heartbeat_interval_sec,json=heartbeatIntervalSec,proto3" json:"heartbeat_interval_sec,omitempty"` // How often to send heartbeat
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterAck) GetHeartbeatIntervalSec() int32 {
	if x != nil {
		return x.HeartbeatIntervalSec
	}
	return 0
}

// Heartbeat: Agent sends periodic heartbeat
type Heartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent_id: Must equal Envelope.agent_id if present (server validates consistency)
	AgentId       string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Paused        bool   `protobuf:"varint,2,opt,name=paused,proto3" json:"paused,omitempty"`                              // Whether agent is paused
	RunningJobs   int32  `protobuf:"varint,3,opt,name=running_jobs,json=runningJobs,proto3" json:"running_jobs,omitempty"` // Current number of running jobs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Heartbeat) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *Heartbeat) GetRunningJobs() int32 {
	if x != nil {
		return x.RunningJobs
	}
	return 0
}

// HeartbeatAck: Server acknowledges heartbeat
type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Header: HTTP header key/value
type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *Header) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Header) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// ForwardHttpRequest: forward request to local service
type ForwardHttpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`                                  // Local service URL (e.g., http://127.0.0.1:8080/api)
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`                            // HTTP method (default POST)
	Headers       []*Header              `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`                          // Optional headers to pass through
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`                                // Optional raw body (UTF-8 or binary)
	TimeoutSec    int32                  `protobuf:"varint,5,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"` // Optional request timeout (seconds)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardHttpRequest) Reset() {
	*x = ForwardHttpRequest{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardHttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardHttpRequest) ProtoMessage() {}

func (x *ForwardHttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardHttpRequest.ProtoReflect.Descriptor instead.
func (*ForwardHttpRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *ForwardHttpRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ForwardHttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ForwardHttpRequest) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ForwardHttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ForwardHttpRequest) GetTimeoutSec() int32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

// STSCreds: STS temporary credentials for OSS access
type STSCreds struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId     string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	AccessKeySecret string                 `protobuf:"bytes,2,opt,name=access_key_secret,json=accessKeySecret,proto3" json:"access_key_secret,omitempty"`
	SecurityToken   string                 `protobuf:"bytes,3,opt,name=security_token,json=securityToken,proto3" json:"security_token,omitempty"`
	Endpoint        string                 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                             // OSS endpoint (e.g., oss-cn-hangzhou.aliyuncs.com)
	Bucket          string                 `protobuf:"bytes,5,opt,name=bucket,proto3" json:"bucket,omitempty"`                                 // Bucket name
	ExpiresAtMs     int64                  `protobuf:"varint,6,opt,name=expires_at_ms,json=expiresAtMs,proto3" json:"expires_at_ms,omitempty"` // Expiration timestamp (Unix milliseconds) - for agent to check validity
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *STSCreds) Reset() {
	*x = STSCreds{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *STSCreds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*STSCreds) ProtoMessage() {}

func (x *STSCreds) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use STSCreds.ProtoReflect.Descriptor instead.
func (*STSCreds) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *STSCreds) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *STSCreds) GetAccessKeySecret() string {
	if x != nil {
		return x.AccessKeySecret
	}
	return ""
}

func (x *STSCreds) GetSecurityToken() string {
	if x != nil {
		return x.SecurityToken
	}
	return ""
}

func (x *STSCreds) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *STSCreds) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *STSCreds) GetExpiresAtMs() int64 {
	if x != nil {
		return x.ExpiresAtMs
	}
	return 0
}

// OSSAccess: OSS access credentials (presigned URL or STS)
// Exactly one of presigned_url or sts must be set.
type OSSAccess struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Auth:
	//
	//	*OSSAccess_PresignedUrl
	//	*OSSAccess_Sts
	Auth          isOSSAccess_Auth `protobuf_oneof:"auth"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSSAccess) Reset() {
	*x = OSSAccess{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSSAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSSAccess) ProtoMessage() {}

func (x *OSSAccess) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSSAccess.ProtoReflect.Descriptor instead.
func (*OSSAccess) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *OSSAccess) GetAuth() isOSSAccess_Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *OSSAccess) GetPresignedUrl() string {
	if x != nil {
		if x, ok := x.Auth.(*OSSAccess_PresignedUrl); ok {
			return x.PresignedUrl
		}
	}
	return ""
}

func (x *OSSAccess) GetSts() *STSCreds {
	if x != nil {
		if x, ok := x.Auth.(*OSSAccess_Sts); ok {
			return x.Sts
		}
	}
	return nil
}

type isOSSAccess_Auth interface {
	isOSSAccess_Auth()
}

type OSSAccess_PresignedUrl struct {
	PresignedUrl string `protobuf:"bytes,1,opt,name=presigned_url,json=presignedUrl,proto3,oneof"` // Presigned URL for direct access (GET for input, PUT for output)
}

type OSSAccess_Sts struct {
	Sts *STSCreds `protobuf:"bytes,2,opt,name=sts,proto3,oneof"` // STS temporary credentials
}

func (*OSSAccess_PresignedUrl) isOSSAccess_Auth() {}

func (*OSSAccess_Sts) isOSSAccess_Auth() {}

// RequestJob: Agent requests a job from cloud
type RequestJob struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent_id: Must equal Envelope.agent_id if present (server validates consistency)
	AgentId        string   `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Capabilities   []string `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                            // Optional: agent capabilities/tags
	MaxConcurrency int32    `protobuf:"varint,3,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"` // Optional: max concurrent jobs (override from Register)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestJob) Reset() {
	*x = RequestJob{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestJob) ProtoMessage() {}

func (x *RequestJob) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestJob.ProtoReflect.Descriptor instead.
func (*RequestJob) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *RequestJob) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RequestJob) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RequestJob) GetMaxConcurrency() int32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

// JobAssigned: Cloud assigns a job to agent
type JobAssigned struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	JobId       string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                      // UUID of the job
	AttemptId   int32                  `protobuf:"varint,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`         // Attempt number (starts at 1) - required for idempotent output paths
	LeaseId     string                 `protobuf:"bytes,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`                // Lease identifier (reserved for future lease renewal)
	LeaseTtlSec int32                  `protobuf:"varint,4,opt,name=lease_ttl_sec,json=leaseTtlSec,proto3" json:"lease_ttl_sec,omitempty"` // Lease TTL in seconds (reserved for future)
	// Input download access
	InputDownload *OSSAccess `protobuf:"bytes,5,opt,name=input_download,json=inputDownload,proto3" json:"input_download,omitempty"` // Presigned GET URL or STS for downloading input
	InputKey      string     `protobuf:"bytes,10,opt,name=input_key,json=inputKey,proto3" json:"input_key,omitempty"`               // Input OSS key (for extracting file extension)
	// Output upload access
	OutputUpload *OSSAccess `protobuf:"bytes,6,opt,name=output_upload,json=outputUpload,proto3" json:"output_upload,omitempty"` // Presigned PUT URL or STS for uploading output
	// Output path information
	// VALIDATION RULES (server MUST enforce before assigning job):
	// - If output_upload uses presigned_url: output_key MUST be set, and presigned_url must target that exact key.
	// - If output_upload uses STS: output_prefix MUST be set, agent may write any key under this prefix.
	// Server must reject job assignment if these rules are violated.
	OutputPrefix     string              `protobuf:"bytes,7,opt,name=output_prefix,json=outputPrefix,proto3" json:"output_prefix,omitempty"`                                               // Output key prefix (e.g., "jobs/{job_id}/{attempt_id}/") - required if using STS
	OutputKey        string              `protobuf:"bytes,8,opt,name=output_key,json=outputKey,proto3" json:"output_key,omitempty"`                                                        // Specific output key - required if using presigned_url
	Command          string              `protobuf:"bytes,9,opt,name=command,proto3" json:"command,omitempty"`                                                                             // Command to execute (e.g., "python C:/scripts/analyze.py {input} {output}")
	JobType          JobTypeEnum         `protobuf:"varint,11,opt,name=job_type,json=jobType,proto3,enum=control.JobTypeEnum" json:"job_type,omitempty"`                                   // Job type (default: COMMAND)
	ForwardHttp      *ForwardHttpRequest `protobuf:"bytes,12,opt,name=forward_http,json=forwardHttp,proto3" json:"forward_http,omitempty"`                                                 // Forward HTTP request configuration
	InputForwardMode InputForwardMode    `protobuf:"varint,13,opt,name=input_forward_mode,json=inputForwardMode,proto3,enum=control.InputForwardMode" json:"input_forward_mode,omitempty"` // Input forwarding mode for forward jobs
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *JobAssigned) Reset() {
	*x = JobAssigned{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAssigned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAssigned) ProtoMessage() {}

func (x *JobAssigned) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAssigned.ProtoReflect.Descriptor instead.
func (*JobAssigned) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

func (x *JobAssigned) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobAssigned) GetAttemptId() int32 {
	if x != nil {
		return x.AttemptId
	}
	return 0
}

func (x *JobAssigned) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *JobAssigned) GetLeaseTtlSec() int32 {
	if x != nil {
		return x.LeaseTtlSec
	}
	return 0
}

func (x *JobAssigned) GetInputDownload() *OSSAccess {
	if x != nil {
		return x.InputDownload
	}
	return nil
}

func (x *JobAssigned) GetInputKey() string {
	if x != nil {
		return x.InputKey
	}
	return ""
}

func (x *JobAssigned) GetOutputUpload() *OSSAccess {
	if x != nil {
		return x.OutputUpload
	}
	return nil
}

func (x *JobAssigned) GetOutputPrefix() string {
	if x != nil {
		return x.OutputPrefix
	}
	return ""
}

func (x *JobAssigned) GetOutputKey() string {
	if x != nil {
		return x.OutputKey
	}
	return ""
}

func (x *JobAssigned) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *JobAssigned) GetJobType() JobTypeEnum {
	if x != nil {
		return x.JobType
	}
	return JobTypeEnum_JOB_TYPE_UNKNOWN
}

func (x *JobAssigned) GetForwardHttp() *ForwardHttpRequest {
	if x != nil {
		return x.ForwardHttp
	}
	return nil
}

func (x *JobAssigned) GetInputForwardMode() InputForwardMode {
	if x != nil {
		return x.InputForwardMode
	}
	return InputForwardMode_INPUT_FORWARD_MODE_UNSPECIFIED
}

// JobStatus: Agent reports job execution status
type JobStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                  // Job identifier
	AttemptId     int32                  `protobuf:"varint,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`     // Attempt number
	Status        JobStatusEnum          `protobuf:"varint,3,opt,name=status,proto3,enum=control.JobStatusEnum" json:"status,omitempty"` // Current status: RUNNING/SUCCEEDED/FAILED/ASSIGNED/CANCELED/LOST
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                           // Optional: status message or error description
	OutputKey     string                 `protobuf:"bytes,5,opt,name=output_key,json=outputKey,proto3" json:"output_key,omitempty"`      // Output key for consistency check (required on SUCCEEDED if output file exists)
	Stdout        string                 `protobuf:"bytes,6,opt,name=stdout,proto3" json:"stdout,omitempty"`                             // Optional: command stdout output (truncated if too long)
	Stderr        string                 `protobuf:"bytes,7,opt,name=stderr,proto3" json:"stderr,omitempty"`                             // Optional: command stderr output (truncated if too long, typically for FAILED status)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatus) Reset() {
	*x = JobStatus{}
	mi := &file_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatus) ProtoMessage() {}

func (x *JobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatus.ProtoReflect.Descriptor instead.
func (*JobStatus) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{11}
}

func (x *JobStatus) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStatus) GetAttemptId() int32 {
	if x != nil {
		return x.AttemptId
	}
	return 0
}

func (x *JobStatus) GetStatus() JobStatusEnum {
	if x != nil {
		return x.Status
	}
	return JobStatusEnum_JOB_STATUS_UNKNOWN
}

func (x *JobStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JobStatus) GetOutputKey() string {
	if x != nil {
		return x.OutputKey
	}
	return ""
}

func (x *JobStatus) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *JobStatus) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\acontrol\"\xf3\x03\n" +
	"\bEnvelope\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12/\n" +
	"\bregister\x18\n" +
	" \x01(\v2\x11.control.RegisterH\x00R\bregister\x122\n" +
	"\theartbeat\x18\v \x01(\v2\x12.control.HeartbeatH\x00R\theartbeat\x129\n" +
	"\fregister_ack\x18\f \x01(\v2\x14.control.RegisterAckH\x00R\vregisterAck\x12<\n" +
	"\rheartbeat_ack\x18\r \x01(\v2\x15.control.HeartbeatAckH\x00R\fheartbeatAck\x126\n" +
	"\vrequest_job\x18\x0e \x01(\v2\x13.control.RequestJobH\x00R\n" +
	"requestJob\x129\n" +
	"\fjob_assigned\x18\x0f \x01(\v2\x14.control.JobAssignedH\x00R\vjobAssigned\x123\n" +
	"\n" +
	"job_status\x18\x10 \x01(\v2\x12.control.JobStatusH\x00R\tjobStatusB\t\n" +
	"\apayload\"\x8b\x01\n" +
	"\bRegister\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vagent_token\x18\x02 \x01(\tR\n" +
	"agentToken\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12'\n" +
	"\x0fmax_concurrency\x18\x04 \x01(\x05R\x0emaxConcurrency\"w\n" +
	"\vRegisterAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\x16heartbeat_interval_sec\x18\x03 \x01(\x05R\x14heartbeatIntervalSec\"a\n" +
	"\tHeartbeat\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06paused\x18\x02 \x01(\bR\x06paused\x12!\n" +
	"\frunning_jobs\x18\x03 \x01(\x05R\vrunningJobs\"(\n" +
	"\fHeartbeatAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"0\n" +
	"\x06Header\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x9e\x01\n" +
	"\x12ForwardHttpRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12)\n" +
	"\aheaders\x18\x03 \x03(\v2\x0f.control.HeaderR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12\x1f\n" +
	"\vtimeout_sec\x18\x05 \x01(\x05R\n" +
	"timeoutSec\"\xd9\x01\n" +
	"\bSTSCreds\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\x12*\n" +
	"\x11access_key_secret\x18\x02 \x01(\tR\x0faccessKeySecret\x12%\n" +
	"\x0esecurity_token\x18\x03 \x01(\tR\rsecurityToken\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06bucket\x18\x05 \x01(\tR\x06bucket\x12\"\n" +
	"\rexpires_at_ms\x18\x06 \x01(\x03R\vexpiresAtMs\"a\n" +
	"\tOSSAccess\x12%\n" +
	"\rpresigned_url\x18\x01 \x01(\tH\x00R\fpresignedUrl\x12%\n" +
	"\x03sts\x18\x02 \x01(\v2\x11.control.STSCredsH\x00R\x03stsB\x06\n" +
	"\x04auth\"t\n" +
	"\n" +
	"RequestJob\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x12'\n" +
	"\x0fmax_concurrency\x18\x03 \x01(\x05R\x0emaxConcurrency\"\xab\x04\n" +
	"\vJobAssigned\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\x05R\tattemptId\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\tR\aleaseId\x12\"\n" +
	"\rlease_ttl_sec\x18\x04 \x01(\x05R\vleaseTtlSec\x129\n" +
	"\x0einput_download\x18\x05 \x01(\v2\x12.control.OSSAccessR\rinputDownload\x12\x1b\n" +
	"\tinput_key\x18\n" +
	" \x01(\tR\binputKey\x127\n" +
	"\routput_upload\x18\x06 \x01(\v2\x12.control.OSSAccessR\foutputUpload\x12#\n" +
	"\routput_prefix\x18\a \x01(\tR\foutputPrefix\x12\x1d\n" +
	"\n" +
	"output_key\x18\b \x01(\tR\toutputKey\x12\x18\n" +
	"\acommand\x18\t \x01(\tR\acommand\x12/\n" +
	"\bjob_type\x18\v \x01(\x0e2\x14.control.JobTypeEnumR\ajobType\x12>\n" +
	"\fforward_http\x18\f \x01(\v2\x1b.control.ForwardHttpRequestR\vforwardHttp\x12G\n" +
	"\x12input_forward_mode\x18\r \x01(\x0e2\x19.control.InputForwardModeR\x10inputForwardMode\"\xda\x01\n" +
	"\tJobStatus\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\x05R\tattemptId\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.control.JobStatusEnumR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"output_key\x18\x05 \x01(\tR\toutputKey\x12\x16\n" +
	"\x06stdout\x18\x06 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\a \x01(\tR\x06stderr*\xb7\x01\n" +
	"\rJobStatusEnum\x12\x16\n" +
	"\x12JOB_STATUS_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13JOB_STATUS_ASSIGNED\x10\x01\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14JOB_STATUS_SUCCEEDED\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x04\x12\x17\n" +
	"\x13JOB_STATUS_CANCELED\x10\x05\x12\x13\n" +
	"\x0fJOB_STATUS_LOST\x10\x06*T\n" +
	"\vJobTypeEnum\x12\x14\n" +
	"\x10JOB_TYPE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10JOB_TYPE_COMMAND\x10\x01\x12\x19\n" +
	"\x15JOB_TYPE_FORWARD_HTTP\x10\x02*u\n" +
	"\x10InputForwardMode\x12\"\n" +
	"\x1eINPUT_FORWARD_MODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16INPUT_FORWARD_MODE_URL\x10\x01\x12!\n" +
	"\x1dINPUT_FORWARD_MODE_LOCAL_FILE\x10\x02B-Z+github.com/xiresource/proto/control;controlb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_control_proto_goTypes = []any{
	(JobStatusEnum)(0),         // 0: control.JobStatusEnum
	(JobTypeEnum)(0),           // 1: control.JobTypeEnum
	(InputForwardMode)(0),      // 2: control.InputForwardMode
	(*Envelope)(nil),           // 3: control.Envelope
	(*Register)(nil),           // 4: control.Register
	(*RegisterAck)(nil),        // 5: control.RegisterAck
	(*Heartbeat)(nil),          // 6: control.Heartbeat
	(*HeartbeatAck)(nil),       // 7: control.HeartbeatAck
	(*Header)(nil),             // 8: control.Header
	(*ForwardHttpRequest)(nil), // 9: control.ForwardHttpRequest
	(*STSCreds)(nil),           // 10: control.STSCreds
	(*OSSAccess)(nil),          // 11: control.OSSAccess
	(*RequestJob)(nil),         // 12: control.RequestJob
	(*JobAssigned)(nil),        // 13: control.JobAssigned
	(*JobStatus)(nil),          // 14: control.JobStatus
}
var file_control_proto_depIdxs = []int32{
	4,  // 0: control.Envelope.register:type_name -> control.Register
	6,  // 1: control.Envelope.heartbeat:type_name -> control.Heartbeat
	5,  // 2: control.Envelope.register_ack:type_name -> control.RegisterAck
	7,  // 3: control.Envelope.heartbeat_ack:type_name -> control.HeartbeatAck
	12, // 4: control.Envelope.request_job:type_name -> control.RequestJob
	13, // 5: control.Envelope.job_assigned:type_name -> control.JobAssigned
	14, // 6: control.Envelope.job_status:type_name -> control.JobStatus
	8,  // 7: control.ForwardHttpRequest.headers:type_name -> control.Header
	10, // 8: control.OSSAccess.sts:type_name -> control.STSCreds
	11, // 9: control.JobAssigned.input_download:type_name -> control.OSSAccess
	11, // 10: control.JobAssigned.output_upload:type_name -> control.OSSAccess
	1,  // 11: control.JobAssigned.job_type:type_name -> control.JobTypeEnum
	9,  // 12: control.JobAssigned.forward_http:type_name -> control.ForwardHttpRequest
	2,  // 13: control.JobAssigned.input_forward_mode:type_name -> control.InputForwardMode
	0,  // 14: control.JobStatus.status:type_name -> control.JobStatusEnum
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	file_control_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Register)(nil),
		(*Envelope_Heartbeat)(nil),
		(*Envelope_RegisterAck)(nil),
		(*Envelope_HeartbeatAck)(nil),
		(*Envelope_RequestJob)(nil),
		(*Envelope_JobAssigned)(nil),
		(*Envelope_JobStatus)(nil),
	}
	file_control_proto_msgTypes[8].OneofWrappers = []any{
		(*OSSAccess_PresignedUrl)(nil),
		(*OSSAccess_Sts)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		EnumInfos:         file_control_proto_enumTypes,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
